### ISSUE TITLE
How can I generate a log file, which is needed during training the RotNet?

### ISSUE THREAD

**Issue by yurui-q** [gidariss/FeatureLearningRotNet#19]
I was training a RotNet of CIFAR10, when I run the command, "python main.py --exp=CIFAR10_RotNet_NIN4bloc", an error occurs.

The error occurs at 
algorithm = getattr(alg, config['algorithm_type'])(config)  of main.py.
it says, 
OSError: [Errno 22] Invalid argument: 'E:\\FeatureLearningRotNet-master\\experiments\\CIFAR10_RotNet_NIN4blocks\\logs\\LOG_INFO_2020-08-06_17:02:54.623166.txt'

I suppose a log file is needed here but I didn't see it in the log folder. Should I add some lines to generate the log?

**Comment by HardworkingLittlequ** [comment]
@little-jones Hello! How did you address this problem?
