### ISSUE TITLE
Pascal experiments code or models?

### ISSUE THREAD

**Issue by jason718** [gidariss/FeatureLearningRotNet#2]
Do you use some pytorch version of pascal det., cls., and seg. code? Or do you convert your model into caffemodel?

**Comment by gidariss** [comment]
I convert the models on caffe format and use the publicly available caffe code. I uploaded the readme.md with link to a model converted to caffe format.

**Comment by polo5** [comment]
Could you point to the caffe repos that you used for classification, detection and segmentation so we can reproduce your results? 

I can only find [this repository] (https://github.com/philkr/voc-classification) for classification (and the future branch refered to doesn't compile for me on CPU...)

**Comment by jason718** [comment]
Can you share your converting code? Or are you using the something like pytorch-caffe-darknet-convert?

**Comment by polo5** [comment]
+1. It would also be nice for instance to have the configuration you used for classification scores (https://github.com/philkr/voc-classification). I can't reproduce the results in your paper with that repo.

**Comment by gidariss** [comment]
#jason718

I updated the github repo with the a script that converts a pytorch alexnet model to a caffe model. It is inside the directory "extras". The same directory also has a script that converts the caffe alexnet model to fully convolutional for the segmentation experiments. When I find time I will update the README with instructions for that part. However, it's pretty easy to use the conversion script: after having install caffe you run the command:

python extras/convert_alexnet_from_pytorch2caffe.py --src=[path to pytorch model] --dst=[path to caffe mode]

**Comment by iamgeo92** [comment]
hi @gidariss  , Does the script also contains the code for rescaling of  Kraehenbuehl et al, ICLR 2016.
