### ISSUE TITLE
about accuracy.

### ISSUE THREAD

**Issue by creat2012** [gidariss/FeatureLearningRotNet#3]
i run the script, then it begin to train.
what i want know is the accuracy. so, what should i do?

**Comment by zzz1515151** [comment]
I have found out that the authors omit the detail code of function train_step, evaluation_step. Can anyone tell be why?

**Comment by zzz1515151** [comment]
Sorry I didn't read all the codes. The author overwrite the training function in multiple sub-classes. It is the python version or something else that make the display module omit accuracy and loss output. I have fixed it by myself and it worked fine.

**Comment by Pengyujiao** [comment]
> Sorry I didn't read all the codes. The author overwrite the training function in multiple sub-classes. It is the python version or something else that make the display module omit accuracy and loss output. I have fixed it by myself and it worked fine.

Excuse me, I am a beginner, I want to ask you a question: the author omitted the detail code of function train_step, evaluation_step, without this part of the code, is not training? Did you complete it? Looking forward to your reply. Thank you

**Comment by zzz1515151** [comment]
As I can remember, the author didn't omit the training and evaluation
codes. These code were not written in the main file, but were overloaded in
other files. I do remember that i found inner-class functions with the same
name in other files that describe the training process. Hope this helps.

**Comment by Pengyujiao** [comment]
Sorry, I didn't look at the code carefully before. I have studied it carefully these two days and found that the code can work completely.Thanks again for your reply. @zzz1515151
