### ISSUE TITLE
Unable to reproduce the ImageNet Linear Classification Results

### ISSUE THREAD

**Issue by WangFeng18** [gidariss/FeatureLearningRotNet#9]
Hello, I am really attracted by your work, which is precise and effective. But when i clone your code and run the run_imagenet_based_unsupervised_feature_experiments.sh script(I used your pretrained model so comment the training command) to test the linear classification, but I got the following results, after runing around 25 epochs, 
![image](https://user-images.githubusercontent.com/43294876/59647029-27399b80-91ac-11e9-8652-b5d3f5354442.png) Especially the conv3,4,5, the results are so low. Maybe  I have ommited some important details. Can you give me some advice?

**Comment by gidariss** [comment]
Hello. Can you provide the log file generated when running the run_imagenet_based_unsupervised_feature_experiments.sh script. It would be easier to help you this way.

**Comment by WangFeng18** [comment]
@gidariss sorry i have found the problem. There are some problems with my imagenet dataset, i have fixed it. And  i will closed the issue. Thank you!

**Comment by ZhangRui111** [comment]
> @gidariss sorry i have found the problem. There are some problems with my imagenet dataset, i have fixed it. And i will closed the issue. Thank you!

Thanks for your issue. I think we made the same error.
